---
title: "run_scripts"
output: html_document
---

Part 0: libraries
```{r}
library(tidyverse)
library(tidyr)
library(dplyr) 
library(readr) 
library(lubridate) 
library(ggplot2)

otp_simulated <- read_csv("~/Desktop/Datascience in R/final_project/data/otp_simulated.csv")
ridership_simulated <- read_csv("~/Desktop/Datascience in R/final_project/data/ridership_simulated.csv")
```

Part 1: data completeness
```{r}
# counts the number of NAs in each column and summarizes it into a dataframe - data looks complete
Na_count_otp_simulated <- otp_simulated %>%
  summarise(across(everything(), ~ sum(is.na(.)))) %>%
  pivot_longer(everything(), names_to = "column", values_to = "na_count") %>%
  arrange(desc(na_count))

Na_count_ridership_simulated <- ridership_simulated %>%
  summarise(across(everything(), ~ sum(is.na(.)))) %>%
  pivot_longer(everything(), names_to = "column", values_to = "na_count") %>%
  arrange(desc(na_count))
```


Part 2: univariate analysis
```{r}

```

Part 3: bivariate analysis

Part 4: higher level analysis
```{r}
source("~/Desktop/Datascience in R/final_project/scripts/aggregate.R")
source("~/Desktop/Datascience in R/final_project/scripts/mapping.R")
source("~/Desktop/Datascience in R/final_project/scripts/analysis.R")
source("~/Desktop/Datascience in R/final_project/scripts/utilities.R")

ridershp_aggregated <- aggregate_ridership(ridership_simulated)
otp_aggregated <- aggregate_otp(otp_simulated)

merged_dataset <- map_ridership(ridershp_aggregated, otp_aggregated)

# Generate the summary and priority categories
hourly_result <- assign_and_split_priority(merged_dataset)

# Access full summary
full_summary <- hourly_result$summary

# Access subsets
Late <- hourly_result$Late
Early <- hourly_result$Early
On_Time <- hourly_result$On_Time

library(ggplot2)

late_subset <- filter_routes(full_summary, unique(Late$Route))
early_subset <- filter_routes(full_summary, unique(Early$Route))

hourly_result <- full_summary %>%
  mutate(
    highlight = case_when(
      Route %in% late_subset$Route ~ "Late",
      Route %in% early_subset$Route ~ "Early",
      TRUE ~ "Other"
    )
  )


# Plot
ggplot(hourly_result, aes(x = Hour, y = total_riders, group = Route)) +
  geom_line(aes(color = highlight), size = 1) +
  scale_color_manual(values = c(
    "Late" = "red",
    "Early" = "blue",
    "Other" = "gray70"
  ))  +
  labs(
    title = "Ridership per Hour by Route",
    x = "Hour of Day",
    y = "Total Riders",
    color = "Group"
  ) +
  theme_minimal()

ggplot(late_subset, aes(x = Hour, y = total_riders, color = as.factor(Route))) +
  geom_line(size = 1) +
  labs(
    title = "Routes that are Delayed by 5 minutes or More",
    x = "Hour of Day",
    y = "Total Riders",
    color = "Route"
  ) +
  theme_minimal()

ggplot(early_subset, aes(x = Hour, y = total_riders, color = as.factor(Route))) +
  geom_line(size = 1) +
  labs(
    title = "Routes that are Early by 5 minutes or More",
    x = "Hour of Day",
    y = "Total Riders",
    color = "Route"
  ) +
  theme_minimal()


priority_routes <- common_routes(early_subset, late_subset)
priority_routes <- filter_routes(full_summary, priority_routes)


```


```{r}
ggplot(priority_routes, aes(x = Hour, y = total_riders, color = as.factor(Route))) +
  geom_line(size = 1) +
  labs(
    title = "High-Priority Stops: Both Early and Late!",
    x = "Hour of Day",
    y = "Total Riders",
    color = "Route"
  ) +
  theme_minimal()

ggplot(priority_routes, aes(x = Hour, y = factor(Route), fill = avg_delay_min)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(
    low = "blue",       # early
    mid = "white",     # on-time
    high = "red",       # late
    midpoint = 0,
    limits = c(-20, 20),
    name = "Avg Delay (min)"
  ) +
  labs(
    x = "Hour of Day",
    y = "Route",
    title = "Heatmap of Average Delay by Route and Hour"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 8),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

ggplot(priority_routes, aes(x = Hour, y = factor(Route), fill = avg_delay_min, alpha = total_riders)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0, limits = c(-5,5), name = "Avg Delay (min)") +
  scale_alpha(range = c(0.3, 1), name = "Riders (opacity)") +
  labs(x = "Hour of Day", y = "Route", title = "Delay by Hour and Route (Alpha = Riders)") +
  theme_minimal()

```

