---
title: "run_scripts"
output: html_document
---

Part 0: libraries
```{r}
library(tidyverse)
library(tidyr)
library(dplyr) 
library(readr) 
library(lubridate) 
library(ggplot2)

otp_simulated <- read_csv("~/Desktop/Datascience in R/final_project/data/otp_simulated.csv")
ridership_simulated <- read_csv("~/Desktop/Datascience in R/final_project/data/ridership_simulated.csv")
```

Part 1: data completeness
```{r}
# counts the number of NAs in each column and summarizes it into a dataframe - data looks complete
Na_count_otp_simulated <- otp_simulated %>%
  summarise(across(everything(), ~ sum(is.na(.)))) %>%
  pivot_longer(everything(), names_to = "column", values_to = "na_count") %>%
  arrange(desc(na_count))

Na_count_ridership_simulated <- ridership_simulated %>%
  summarise(across(everything(), ~ sum(is.na(.)))) %>%
  pivot_longer(everything(), names_to = "column", values_to = "na_count") %>%
  arrange(desc(na_count))
```


Part 2: univariate analysis
```{r}
# otp
# counts for days in may
ggplot(otp_simulated, aes(x = Date)) +
  geom_histogram(stat = "count", fill = "steelblue", color = "black") +
  labs(title = "Number of Records per Date",
       x = "Date",
       y = "Count") +
  theme_minimal()

# route
ggplot(otp_simulated, aes(x = Route)) +
  geom_histogram(stat = "count", fill = "steelblue", color = "black") +
  labs(title = "Number of Records per Route",
       x = "Route",
       y = "Count") +
  theme_minimal()

# stops
ggplot(otp_simulated, aes(x = Stop)) +
  geom_histogram(stat = "count", fill = "steelblue", color = "black") +
  labs(title = "Number of Records for Stops",
       x = "Stop",
       y = "Count") +
  theme_minimal()

# delays
ggplot(otp_simulated, aes(x = Delay.Sec)) +
  geom_histogram(stat = "count", fill = "steelblue", color = "black") +
  labs(title = "Number of Records per Date",
       x = "Date",
       y = "Count") +
  theme_minimal()
```

Part 3: bivariate analysis

Part 4: higher level analysis